jQuery( document ).ready(function() {
    jQuery('#page-transition-in').select2();
    jQuery('#page-transition-out').select2();
    jQuery('#slider-arrows-hover').select2();
    jQuery('#_startup_reloaded_services_icon').select2();
    jQuery('#_startup_reloaded_milestones_icon').select2();
    jQuery('#_startup_reloaded_slider_title_animation').select2();
    jQuery('#_startup_reloaded_slider_content_animation').select2();
    jQuery('#_startup_reloaded_slider_button_animation').select2();
    jQuery('#_startup_reloaded_team_icon_1').select2();
    jQuery('#_startup_reloaded_team_icon_2').select2();
    jQuery('#_startup_reloaded_team_icon_3').select2();
    jQuery('#_startup_reloaded_team_icon_4').select2();
    jQuery('#_startup_reloaded_team_page').select2();
    jQuery('#_startup_reloaded_pricing_icon_1').select2();
    jQuery('#_startup_reloaded_pricing_icon_2').select2();
    jQuery('#_startup_reloaded_pricing_icon_3').select2();
    jQuery('#_startup_reloaded_pricing_icon_4').select2();
});